// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgw0a2-7rAUlEJPYHpejZOrhdwACswJ3Q',
    appId: '1:415544312004:web:c67b2fe1eb2d853b984991',
    messagingSenderId: '415544312004',
    projectId: 'midnightclub-1dbf9',
    authDomain: 'midnightclub-1dbf9.firebaseapp.com',
    storageBucket: 'midnightclub-1dbf9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXdgCzRLGG42bgcMIMRXt3NLgdWBYOHtQ',
    appId: '1:415544312004:android:323cf772e0d57bf5984991',
    messagingSenderId: '415544312004',
    projectId: 'midnightclub-1dbf9',
    storageBucket: 'midnightclub-1dbf9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJdrMd8kqo0PnDGLZVKhZO_AbaVp7FyCw',
    appId: '1:415544312004:ios:240de90561c7b182984991',
    messagingSenderId: '415544312004',
    projectId: 'midnightclub-1dbf9',
    storageBucket: 'midnightclub-1dbf9.appspot.com',
    iosBundleId: 'com.example.midnightclubMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJdrMd8kqo0PnDGLZVKhZO_AbaVp7FyCw',
    appId: '1:415544312004:ios:67a4adc6f7bf6c07984991',
    messagingSenderId: '415544312004',
    projectId: 'midnightclub-1dbf9',
    storageBucket: 'midnightclub-1dbf9.appspot.com',
    iosBundleId: 'com.example.midnightclubMain.RunnerTests',
  );
}
